name: cldr
author: Dart Authors <misc@dartlang.org>
version: 0.0.6
homepage: http://github.com/dart-lang/cldr
description: Mechanisms to extract data from Cldr.
dependencies:
  args: any
  cli: any
  codegen: any
  http: any
  logging: any
  mockable_filesystem: any
  path: any
dev_dependencies:
  unittest: any
