name: cldr
version: 0.0.1
author: Sean Eagan <seaneagan1@gmail.com>
description: Mechanisms to extract data from Cldr.
homepage: http://github.com/seaneagan/cldr
dependencies:
  args: any
  codegen: any
  crypto: any
  http: any
  logging: any
  path: any
dev_dependencies:
  unittest: any

#TODO: Remove crypto dependency once http://dartbug.com/11358 is fixed.