name: cldr
version: 0.0.1
author: Sean Eagan <seaneagan1@gmail.com>
description: Mechanisms to extract data from Cldr.
homepage: http://github.com/seaneagan/cldr
dependencies:
  args: any
  codegen: any
  crypto: any
  http: any
  logging: any
  path: any
  cli:
    path: C:\Users\se136c\dart\cli
dev_dependencies:
  unittest: any
