name: cldr
version: 0.0.3
author: Dart Authors <misc@dartlang.org>
description: Mechanisms to extract data from Cldr.
homepage: http://github.com/dart-lang/cldr
dependencies:
  args: any
  cli: any
  codegen: any
  http: any
  logging: any
  path: any
dev_dependencies:
  unittest: any
